# General Jekyll Config
permalink: /:title/
paginate_path: /page/:num/
highlighter: rouge
lsi: false

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-archives
  - nokogiri

#Ditaaa Settings
ditaa_output_directory: /assets/ditaa

#Jekyll gist
gist:
  noscript: false

#Archives Settings
jekyll-archives:
  enabled:
    - year
  layout: 'archive'
  permalinks:
    year: '/arsiv/:year/'

# Jekyll SEO
social:
  name: Mertcan GÖKGÖZ
  links:
    - http://twitter.com/mertcangokgoz
    - https://www.linkedin.com/in/mertcangokgoz
    - https://plus.google.com/+MertcanGokgoz
    - https://github.com/MertcanGokgoz
    - https://keybase.io/MertcanGokgoz

webmaster_verifications:
  google: 72uYg4UxAer0YwWdtkU93OGqjNq7ZThpqe0M4KxyvIg
  bing: 2183CAED5258723C183F825A20DF9C4A
  yandex: 67dfe7436c3122f7

lang: tr_TR

#Main Settings
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, .travis.yml, .ruby-version, .bundle, build.sh, vendor, Rakefile]
timezone: 'Europe/Istanbul'
encoding: 'utf-8'

#Markdown Settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md

# Setup
title:            Mertcan GÖKGÖZ - Özgür Yazılım, Sunucu Yönetimi ve Hizmetleri
tagline:          Blog
description:      "Özgür yazılım üzerine GNU/Linux sistemler için sunucu yönetimi, kurulum, yapılandırma, ipuçları hakkında türkçe site"
url:              https://mertcangokgoz.com

author:
  name:           'Mertcan GÖKGÖZ'
  url:            'https://mertcangokgoz.com'
  email:          'admin@mertcangokgoz.com'
  twitter:	      'http://twitter.com/mertcangokgoz'
paginate:         22

# Custom vars
version:          3.0.0

twitter:
  username: mertcangokgoz

github:
repo: https://github.com/MertcanGokgoz
